name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: extism/python-pdk
          path: python-pdk

      - name: Setup Extism and XTP
        run: |
          curl -O https://raw.githubusercontent.com/extism/js-pdk/main/install.sh
          sh install.sh
          curl https://static.dylibso.com/cli/install.sh | sh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install extism-py
        run: |
          rustup target add wasm32-wasi
          cd python-pdk && ./build.py install
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install
        run: |
          npm ci
          npm install -g ejs-lint

      - name: Build
        run: |
          npm run build
  
      - name: Check Rust Version
        run: rustc --version
          
      - name: Run test script
        run: |
          cd tests && ./test.sh

      - name: Run Bindgen Test
        run: |
          sh bindgen-test.sh install
          sh bindgen-test.sh run


